### ISSUE TITLE
运行common.py 报错

### ISSUE THREAD

**Issue by liry-code** [chenshuaikang/meituan#1]
![image](https://user-images.githubusercontent.com/13272700/128956653-5d3c216e-7db2-40cd-90b4-98a424a53a8d.png)

你好，在本地运行common.py 时报错如上，请问代码需要改哪些配置嘛

**Comment by chenshuaikang** [comment]
导致这个问题的可能原因是因为你没有登录，建议尝试以下步骤：

**Comment by chenshuaikang** [comment]
导致这个问题的可能原因是因为你没有登录，建议尝试以下步骤：
1. 登录美团PC版，获取到登录后的cookie
2. 在获取uuid那一步加入该cookie
